# Generated by Django 4.2.6 on 2024-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
