# Generated by Django 4.2.6 on 2024-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_company_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]