# Generated by Django 4.2.6 on 2024-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_monthlysalary_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_date',
            field=models.DateField(default='2024-04-27'),
            preserve_default=False,
        ),
    ]
