# Generated by Django 4.2.6 on 2024-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employee_avatar_employee_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='paid_date',
            field=models.DateField(default=False),
        ),
    ]
