# Generated by Django 4.2.6 on 2024-05-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_monthlysalary_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='paid_date',
        ),
    ]
