# Generated by Django 5.0.7 on 2024-08-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_monthlysalary_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
