# Generated by Django 4.2.6 on 2024-05-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='employee_count',
            field=models.IntegerField(default=0),
        ),
    ]
