# Generated by Django 4.2.6 on 2024-05-23 21:16

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_department_employee_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, related_name='employees', to='hr.department'),
        ),
    ]
