# Generated by Django 4.2.6 on 2024-05-24 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='employee_count',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hr.department'),
        ),
    ]
