# Generated by Django 5.0.7 on 2024-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests', models.IntegerField(default=0)),
                ('exception', models.IntegerField(default=0)),
            ],
        ),
    ]
