# Generated by Django 4.2.6 on 2023-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requeststatistics",
            name="data",
        ),
        migrations.AddField(
            model_name="requeststatistics",
            name="exception",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="requeststatistics",
            name="requests",
            field=models.IntegerField(default=0),
        ),
    ]
